pc1[0]=lan_clients
pc2[0]=lan_clients
pc3[0]=lan_clients
pc4[0]=lan_clients

proxy[0]=lan_clients
proxy[1]=lan_proxy_r1
proxy[image]=kathara-squid

r1[0]=lan_proxy_r1
r1[1]=lan_internet

internet[0]=lan_internet
internet[image]=kathara-nginx
